First UI-task
priyanka0901/UI-task pull request #1
Opened 2017-06-08 08:51 UTC by priyanka0901

2017-06-09 05:38 UTC, priyanka1110 commented on ass1/css/main.css
> +  padding: 6% 10px 2%;
@priyanka0901 Why padding is both in pixel and percentage. Use either percentage or pixel.

2017-06-09 05:40 UTC, priyanka1110 commented
@priyanka0901 Add the proper title and description for the PR.

2017-06-09 09:47 UTC, priyanka0901 commented on ass1/css/main.css
> +  padding: 6% 10px 2%;
fixed

2017-06-12 07:09 UTC, priyanka1110 commented on ass1/css/main.css
> +  font-style: normal;
@priyanka0901 What is the use of this code.

2017-06-12 07:11 UTC, priyanka1110 requested changes

2017-06-12 07:11 UTC, priyanka1110 commented on ass1/index.html
> +    <title>First UI-tak</title>
@priyanka0901 Where is Favicon icon?

2017-06-12 08:56 UTC, priyanka1110 commented on ass1/index.html
> +        <div class="clear"></div>
@priyanka0901  What is the use of clear here.

2017-06-12 08:59 UTC, priyanka1110 commented on ass2/index.html
> +    <h6>Jump to</h6>
@priyanka0901 Why h6 tag here.

2017-06-12 09:00 UTC, priyanka1110 commented on ass2/index.html
> +        <div class="letter-style"><h3>A</h3></div>
@priyanka0901 Class name is not good and `h3` tag for the initial letter. It can be span tag.

2017-06-12 09:03 UTC, priyanka1110 commented on ass2/index.html
> +          <p class="user-name">John Doe (owner)</p>
@priyanka0901 Use `span` tag for owner label.

2017-06-12 09:05 UTC, priyanka1110 commented on ass2/index.html
> +        <button class="make-owner button">Make owner</button>
@priyanka0901 Common styling classes should come first then cutome class or color class
For Ex:
<button class="button make-owner">Make owner </button>

2017-06-12 09:06 UTC, priyanka1110 commented on ass2/index.html
> +      <div>+91 01234567890</div>
@priyanka0901 Why not a tag for the telephone number.

2017-06-12 09:07 UTC, priyanka1110 commented on ass2/index.html
> +      <button class="edit-button button">Edit
@priyanka0901 Close the button.

2017-06-12 09:11 UTC, priyanka1110 commented on ass2/index.html
> +      <button class="sidebar-logout flat-button"><i class="icon-switch"></i>Logout</button>
@priyanka0901 Why button is not inside `li`

2017-06-12 09:16 UTC, priyanka1110 commented on ass2/index.html
> +          <input type="text" name="search" placeholder="Lookup User">
@priyanka0901 This is a search input field so we should use input type `search` instead of `text`

2017-06-12 09:19 UTC, priyanka1110 commented on ass2/index.html
> +      <input type="text" class="form-info" placeholder="Transfer ownership">
@priyanka0901 In design transfer ownership is a header, not input filed.

2017-06-12 09:20 UTC, priyanka0901 commented on ass2/index.html
> +    <h6>Jump to</h6>
So that I dont have to give font-size and font-weight

2017-06-12 09:20 UTC, priyanka1110 commented on ass2/index.html
> +      <input type="text" class="form-info" placeholder="Enter Email Id">
@priyanka0901 In placeholder you asking user to add email id but for input field you are passing input type as `text` instead of `email`

2017-06-12 09:25 UTC, priyanka1110 commented on ass2/css/main.css
> +  width: 220px;
@priyanka0901 Here you have added the width of the sidebar as 220px but for the container, you are adding margin left 250px. Any particular reason.

2017-06-12 09:26 UTC, priyanka1110 commented on ass2/css/main.css
> +.sidebar-options {
@priyanka0901 Why do you need position and height here. As you have already added position fixed and height for the parent class.

2017-06-12 09:29 UTC, priyanka1110 commented on ass2/css/main.css
> +.button {
@priyanka0901 Add height and line height for button

2017-06-12 09:32 UTC, priyanka1110 requested changes

2017-06-12 09:32 UTC, priyanka1110 commented on ass2/css/main.css
> +.icon-search:before {
@priyanka0901 Why you have added icon-search CSS here as it's already available in the icon file.

2017-06-12 09:32 UTC, priyanka0901 commented on ass1/css/main.css
> +  font-style: normal;
removed

2017-06-12 09:32 UTC, priyanka0901 commented on ass1/index.html
> +    <title>First UI-tak</title>
done

2017-06-12 09:32 UTC, priyanka0901 commented on ass1/index.html
> +        <div class="clear"></div>
removed

2017-06-12 09:32 UTC, priyanka0901 commented on ass2/index.html
> +        <div class="letter-style"><h3>A</h3></div>
done

2017-06-12 09:32 UTC, priyanka0901 commented on ass2/index.html
> +          <p class="user-name">John Doe (owner)</p>
done

2017-06-12 09:33 UTC, priyanka0901 commented on ass2/index.html
> +        <button class="make-owner button">Make owner</button>
done

2017-06-12 09:33 UTC, priyanka0901 commented on ass2/index.html
> +      <div>+91 01234567890</div>
done

2017-06-12 09:33 UTC, priyanka0901 commented on ass2/index.html
> +      <button class="edit-button button">Edit
done

2017-06-12 09:33 UTC, priyanka0901 commented on ass2/index.html
> +      <button class="sidebar-logout flat-button"><i class="icon-switch"></i>Logout</button>
done

2017-06-12 09:33 UTC, priyanka0901 commented on ass2/index.html
> +          <input type="text" name="search" placeholder="Lookup User">
done

2017-06-12 09:34 UTC, priyanka0901 commented on ass2/index.html
> +      <input type="text" class="form-info" placeholder="Transfer ownership">
It look like input field

2017-06-12 09:34 UTC, priyanka0901 commented on ass2/index.html
> +      <input type="text" class="form-info" placeholder="Enter Email Id">
done

2017-06-12 09:35 UTC, priyanka0901 commented on ass2/css/main.css
> +  width: 220px;
I have doubt in this would like to discuss in personal

2017-06-12 09:39 UTC, priyanka0901 commented on ass2/css/main.css
> +.sidebar-options {
removed ... did by mistake

2017-06-12 09:44 UTC, priyanka0901 commented on ass2/css/main.css
> +.button {
done

2017-06-12 09:47 UTC, priyanka0901 commented on ass2/css/main.css
> +.icon-search:before {
removed

2017-06-19 00:34 UTC, priyanka1110 commented
@priyanka0901 I don't have access to merge this code. You can merge it.

2017-06-19 00:35 UTC, priyanka1110 approved these changes
LGTM

2017-06-28 17:28 UTC, merged